# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35eb7ca8cdb494ddb683c21e6e1eb2d2b4ccef01a444bc94c65c89b405be679c8debaf92712ea9200c42455fb86871d314c690aaa9b170f274ed9e7d5ad4cc5f

test:
  secret_key_base: a08c61311939ed640a01e39979619e99c9844bac98b47923f991a2a36c81193757b92512beb228c8f91ce50e8bde49d0d7e5199458739f1a03156c807f78f08d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
